name: Android Test CI
on:
 push:
   branches:
     - master
 
jobs:
 build:
   runs-on: windows-latest
 
   steps:
    - uses: actions/checkout@master
    - name: set up JDK 1.8
      uses: actions/setup-java@master
      with:
         java-version: 1.8
    - name: Make Gradle execuDockerfiletable
      run: git update-index --chmod=+x ./gradlew
    - name: Build Release APK
      run: ./gradlew assembleRelease
    - name: Releasing using Hub
      run: ./gradlew app:publishApkRelease
